package com.demo.bean;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cour_id
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    private String courId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.user_id
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cour_name
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    private String courName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cour_desc
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    private String courDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cour_file
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    private String courFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cour_file_name
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    private String courFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.sta_time
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    private String staTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.end_time
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.full_score
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    private Integer fullScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.state
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cour_dir_id
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    private String courDirId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cour_create_time
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    private String courCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public Course(String courId, String userId, String courName, String courDesc, String courFile, String courFileName, String staTime, String endTime, Integer fullScore, String state, String courDirId, String courCreateTime) {
        this.courId = courId;
        this.userId = userId;
        this.courName = courName;
        this.courDesc = courDesc;
        this.courFile = courFile;
        this.courFileName = courFileName;
        this.staTime = staTime;
        this.endTime = endTime;
        this.fullScore = fullScore;
        this.state = state;
        this.courDirId = courDirId;
        this.courCreateTime = courCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public Course() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cour_id
     *
     * @return the value of course.cour_id
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public String getCourId() {
        return courId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cour_id
     *
     * @param courId the value for course.cour_id
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public void setCourId(String courId) {
        this.courId = courId == null ? null : courId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.user_id
     *
     * @return the value of course.user_id
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.user_id
     *
     * @param userId the value for course.user_id
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cour_name
     *
     * @return the value of course.cour_name
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public String getCourName() {
        return courName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cour_name
     *
     * @param courName the value for course.cour_name
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public void setCourName(String courName) {
        this.courName = courName == null ? null : courName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cour_desc
     *
     * @return the value of course.cour_desc
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public String getCourDesc() {
        return courDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cour_desc
     *
     * @param courDesc the value for course.cour_desc
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public void setCourDesc(String courDesc) {
        this.courDesc = courDesc == null ? null : courDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cour_file
     *
     * @return the value of course.cour_file
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public String getCourFile() {
        return courFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cour_file
     *
     * @param courFile the value for course.cour_file
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public void setCourFile(String courFile) {
        this.courFile = courFile == null ? null : courFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cour_file_name
     *
     * @return the value of course.cour_file_name
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public String getCourFileName() {
        return courFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cour_file_name
     *
     * @param courFileName the value for course.cour_file_name
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public void setCourFileName(String courFileName) {
        this.courFileName = courFileName == null ? null : courFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.sta_time
     *
     * @return the value of course.sta_time
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public String getStaTime() {
        return staTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.sta_time
     *
     * @param staTime the value for course.sta_time
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public void setStaTime(String staTime) {
        this.staTime = staTime == null ? null : staTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.end_time
     *
     * @return the value of course.end_time
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.end_time
     *
     * @param endTime the value for course.end_time
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.full_score
     *
     * @return the value of course.full_score
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public Integer getFullScore() {
        return fullScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.full_score
     *
     * @param fullScore the value for course.full_score
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public void setFullScore(Integer fullScore) {
        this.fullScore = fullScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.state
     *
     * @return the value of course.state
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.state
     *
     * @param state the value for course.state
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cour_dir_id
     *
     * @return the value of course.cour_dir_id
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public String getCourDirId() {
        return courDirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cour_dir_id
     *
     * @param courDirId the value for course.cour_dir_id
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public void setCourDirId(String courDirId) {
        this.courDirId = courDirId == null ? null : courDirId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cour_create_time
     *
     * @return the value of course.cour_create_time
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public String getCourCreateTime() {
        return courCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cour_create_time
     *
     * @param courCreateTime the value for course.cour_create_time
     *
     * @mbggenerated Fri Apr 12 21:16:36 CST 2019
     */
    public void setCourCreateTime(String courCreateTime) {
        this.courCreateTime = courCreateTime == null ? null : courCreateTime.trim();
    }
}